### ISSUE TITLE
[BUG] Garbage Collector Is Broken

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [Calamity210/BirbLang#71]
**Describe the bug**
In `birb:ui` when I move the mouse a bit fast or is off the screen and comes back again then I get this exception:

```shell
Unhandled exception:
Concurrent modification during iteration: Instance of 'ListQueue<ASTNode>'.
#0      ListQueue._checkModification (dart:collection/queue.dart:800:7)
#1      _ListQueueIterator.moveNext (dart:collection/queue.dart:910:12)
#2      collectAndSweepGarbage (package:Birb/runtime/runtime.dart:109:38)
#3      visitCompound (package:Birb/runtime/runtime.dart:948:3)
```

**`Full Logs:`**
```shell
PS C:\Users\user\Desktop\Andy\Projects\Birb\BirbLang> dart .\lib\birb.dart .\examples\ui.birb
lib/birb.dart: Warning: Interpreting this as package URI, 'package:Birb/birb.dart'.
1 : 26725049000
0 : 26725048952
0 : 26725048952
0 : 26725048952
0 : 26725048952
1 : 26725049000
0 : 26725048856
0 : 26725048856
0 : 26725048856
0 : 26725048856
0 : 26725048856
0 : 26725048856
0 : 26725048776
0 : 26725048776
Unhandled exception:
Concurrent modification during iteration: Instance of 'ListQueue<ASTNode>'.
#0      ListQueue._checkModification (dart:collection/queue.dart:800:7)
#1      _ListQueueIterator.moveNext (dart:collection/queue.dart:910:12)
#2      collectAndSweepGarbage (package:Birb/runtime/runtime.dart:109:38)
#3      visitCompound (package:Birb/runtime/runtime.dart:948:3)
<asynchronous suspension>
#4      visit (package:Birb/runtime/runtime.dart:282:20)
<asynchronous suspension>
#5      runtimeFunctionCall (package:Birb/runtime/runtime.dart:192:16)
<asynchronous suspension>
#6      runtimeFuncLookup (package:Birb/runtime/runtime.dart:834:18)
<asynchronous suspension>
#7      visitFuncCall (package:Birb/runtime/runtime.dart:905:36)
#8      mouseCallback (package:Birb/external/ui.dart:33:3)
#9      _FfiCallbackmouseCallback (dart:ffi)
#10     FfiTrampoline (dart:ffi)
#11     windowClass.<anonymous closure> (package:Birb/external/ui.dart:99:19)
#12     visitAttAccess (package:Birb/runtime/runtime.dart:1091:67)
<asynchronous suspension>
#13     visit (package:Birb/runtime/runtime.dart:323:20)
<asynchronous suspension>
#14     visitCompound (package:Birb/runtime/runtime.dart:932:35)
<asynchronous suspension>
#15     visit (package:Birb/runtime/runtime.dart:282:20)
<asynchronous suspension>
#16     visitWhile (package:Birb/runtime/runtime.dart:2120:27)
<asynchronous suspension>
#17     visit (package:Birb/runtime/runtime.dart:317:20)
#18     visitCompound (package:Birb/runtime/runtime.dart:932:35)
<asynchronous suspension>
#19     visit (package:Birb/runtime/runtime.dart:282:20)
#20     main (package:Birb/birb.dart:97:11)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)```

**Comment by Calamity210** [comment]
@Andy-Python-Programmer can u confirm that this issue still exists?

**Comment by Andy-Python-Programmer** [comment]
Yeup it seems like its fixed @Calamity210 Closing this :)

**Comment by Andy-Python-Programmer** [comment]
#70
